alias mkm="python3 manage.py makemigrations api"
alias m="python3 manage.py migrate"
alias admin="python3 manage.py createsuperuser"
alias run="python3 manage.py runserver"
alias flush="python3 manage.py flush"
